services:
  tododb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - todoapimysql-net
    environment:
      MYSQL_DATABASE: todo_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  server:
    build:
      context: ./todo-back-end
    ports:
      - 8080:8080
    restart: always
    networks:
      - todoapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://tododb:3306/todo_app_db
      - spring.datasource.username=user
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=update
    depends_on:
      - tododb

    volumes:
      - .m2:/root/.m2
  react:
    # Location to the react.js dockerfile
    build:
      context:
        ./todo-front-end
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: todo-frontend
    environment:
      - VITE_APP_BACKEND_BASE_URL=http://localhost:8080
    ports:
      # Host port:Container port
      - "5173:5173"
    stdin_open: true

networks:
  todoapimysql-net:
