name: Unit Tests

on:
  push:
    branches: [main]
defaults:
  run:
    working-directory: todo-front-end
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

<<<<<<< HEAD
      - name: Install Dev Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm -D install

=======
      - name: Install Dependencies
        run: npm -D install


>>>>>>> 5eeff30027633edb5ba363ac3d8dfcdbb16d52f9
      - name: Run Tests
        run: npm test

      - name: Save cache
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: echo "Cache updated"
